services:
  - type: web
    name: ethiopos-backend-aman
    env: node
    plan: free
    buildCommand: |
      npm install --ignore-scripts && 
      npm rebuild sqlite3
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://ethiopos-frontend.onrender.com
      - key: PRODUCTION_URL
        value: https://ethiopos-frontend.onrender.com